name = "llms-explorer"
compatibility_date = "2023-12-01"

# Required for Pages projects using wrangler.toml
pages_build_output_dir = "dist"

# KV Namespace binding for Astro sessions
# This is required when using Astro with the Cloudflare adapter and sessions enabled
# Without this binding, you'll get the SessionConfigWithoutFlagError even if the
# experimental.session flag is set to true in astro.config.mjs
kv_namespaces = [
  { binding = "SESSION", id = "889af86f97364ca382a869856373b073", preview_id = "your-preview-kv-namespace-id" }
]

# In Cloudflare Pages dashboard, you must also:
# 1. Go to your Pages project > Settings > Functions
# 2. Under "KV namespace bindings", add a binding with:
#    - Variable name: SESSION
#    - KV namespace: (select your namespace)