name = "llms-explorer"
# The compatibility_date specifies the version of the Cloudflare Workers runtime to use
# This date ensures we're using a stable version with all required features
compatibility_date = "2024-09-23"

# The nodejs_compat flag is critical for our application as it enables Node.js compatibility mode
# This allows the use of certain Node.js APIs and modules that would otherwise cause runtime errors
# Without this flag, we would encounter "Module not found" errors for Node.js built-in modules
compatibility_flags = ["nodejs_compat"]

# Required for Pages projects using wrangler.toml
pages_build_output_dir = "dist"

# KV Namespace binding for Astro sessions
# This is required when using Astro with the Cloudflare adapter and sessions enabled
# Without this binding, you'll get the SessionConfigWithoutFlagError even if the
# experimental.session flag is set to true in astro.config.mjs
kv_namespaces = [
  { binding = "SESSION", id = "889af86f97364ca382a869856373b073", preview_id = "889af86f97364ca382a869856373b073" }
]

# Note: For local development with a different preview KV namespace,
# create a separate preview namespace in Cloudflare Dashboard and update the preview_id above

# In Cloudflare Pages dashboard, you must also:
# 1. Go to your Pages project > Settings > Functions
# 2. Under "KV namespace bindings", add a binding with:
#    - Variable name: SESSION
#    - KV namespace: (select your namespace)

# Handling Sharp warnings:
# Cloudflare Workers environment doesn't support the Sharp image processing library
# These warnings can be safely ignored as image optimization is disabled in astro.config.mjs
# with the setting `Image: false` in the compress integration