name: Update Frontend Data

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4
        # This checks out the backend repo where this workflow runs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Using a specific version is recommended

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run data acquisition script
        run: python scripts/acquire_data.py
        # Assuming this script outputs llms_metadata.json to the workspace root

      - name: Run data enrichment script
        run: python scripts/enrich_domains.py
        # Assuming this script reads llms_metadata.json and outputs llms_metadata_enriched.json to the workspace root

      - name: Check if data file exists
        id: check_file
        run: |
          if [ -f "llms_metadata_enriched.json" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Data file llms_metadata_enriched.json not found after running scripts."
            echo "file_exists=false" >> $GITHUB_OUTPUT
            exit 1 # Fail the job if the file is missing
          fi

      - name: Checkout frontend repository
        if: steps.check_file.outputs.file_exists == 'true'
        uses: actions/checkout@v4
        with:
          repository: your-github-username/astro-llms-explorer # <<< Replace with actual frontend repo path
          token: ${{ secrets.YOUR_FRONTEND_REPO_PAT }} # <<< Use a PAT stored as a secret
          path: frontend-repo # Checkout frontend repo into a subdirectory
          ref: main # Specify the branch to checkout and push to

      - name: Copy data file to frontend repo
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          mkdir -p frontend-repo/src/data/
          cp llms_metadata_enriched.json frontend-repo/src/data/llms_metadata.json

      - name: Commit and push changes to frontend repo
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          cd frontend-repo
          git config user.name "GitHub Action Bot"
          git config user.email "action-bot@users.noreply.github.com"
          # Check if there are changes to commit
          if ! git diff --quiet src/data/llms_metadata.json; then
            git add src/data/llms_metadata.json
            git commit -m "Update LLM metadata from backend process"
            git push origin main # Push back to the same branch checked out
            echo "Data file updated and pushed to frontend repository."
          else
            echo "No changes detected in the data file. Nothing to commit."
          fi
        # No need for working-directory here as we cd'd into frontend-repo
